// Model editor: JSON drafts are inexpensive; RDF persistence is explicit and batched.
(function () {
  var controls = '#recognize_btn,#enable_visualize_entity_type,#disable_visualize_entity_type,#show_all_face';
  var drafts = Object.create(null), saved = Object.create(null), manifest = null, pending = false, timer = null;
  var fields = {
    space: [['zone_name','Space Name',''],['zone_c_temp','Cooling Setpoint','°C'],['zone_h_temp','Heating Setpoint','°C'],['zone_collingEER','Cooling COP',''],['zone_HeatingEER','Heating COP',''],['zone_ppsm','Population','person/m²'],['zone_equipment','Equipment Heat','W/m²'],['zone_lighting','Lighting Heat','W/m²'],['zone_infiltration','Infiltration','ACH']],
    wall: [['u_value','Wall U-value','W/(m²·K)'],['volumetric_heat_capacity','Volumetric Heat Capacity','J/(m³·K)'],['thickness','Wall thickness','m'],['reflection','Reflection','']],
    window: [['u_value','Window U-value','W/(m²·K)'],['shgc','Window SHGC',''],['operable','Operable',''],['reflection','Reflection',''],['transparency','Transparency','']]
  };
  UI.space_params = Object.create(null); UI.modelContext = null; UI.settingsVersion = 0; UI.selectedTarget = null;
  function key(t) { return t ? t.type + ':' + t.id : ''; } function own(o,n){return Object.prototype.hasOwnProperty.call(o||{},n);}
  function values(t) { return t && Object.assign({}, saved[key(t)] || t.values || {}, drafts[key(t)] || {}); }
  function dirty(){return Object.keys(drafts).some(function(k){return Object.keys(drafts[k]).length;});}
  function validate(kind,name,raw,all) { if(kind==='space'&&name==='zone_name')return String(raw).trim()&&!/[\r\n]/.test(raw)?'':'A single-line name is required'; var n=Number(raw); if(!isFinite(n))return 'A finite number is required'; if((name==='u_value'||name==='thickness'||/EER/.test(name))&&n<=0)return 'Value must be positive'; if((name==='volumetric_heat_capacity'||/ppsm|equipment|lighting|infiltration/.test(name))&&n<0)return 'Value must be nonnegative'; if(/shgc|operable|reflection|transparency/.test(name)&&(n<0||n>1))return 'Value must be 0–1'; if(kind==='space'&&(name==='zone_c_temp'||name==='zone_h_temp')&&Number(all.zone_h_temp)>Number(all.zone_c_temp))return 'Heating setpoint must not exceed cooling'; return ''; }
  function refresh(){ $(controls).prop('disabled',!!UI.modelBusy||pending); $('#space_level').prop('disabled',!!UI.modelBusy||!manifest||!manifest.levels.length); $('#space_save').prop('disabled',!dirty()||pending||!!UI.modelBusy||!!$('.field-error:not(:empty)').length); $('#space_reset').prop('disabled',!dirty()||pending||!!UI.modelBusy); $('.space-input').prop('disabled',!UI.selectedTarget||pending||!!UI.modelBusy); }
  function highlight(){ $('#space_svg_view [data-space-id],[data-element-id]').each(function(){var t=UI.selectedTarget,ok=t&&((t.type==='space'&&this.getAttribute('data-space-id')===t.id)||(this.getAttribute('data-element-id')===t.id));this.classList.toggle('selected',!!ok);});}
  function flush(){clearTimeout(timer);timer=null;if(UI.modelContext)Skp.send('space_drafts_save',[JSON.stringify({context:UI.modelContext,drafts:drafts})]);}
  function schedule(){clearTimeout(timer);timer=setTimeout(flush,250);}
  function render(){var t=UI.selectedTarget,table=$('#building_params_table').empty();if(!t){$('#space_selection_hint').text('Select a space, wall, or window above. Changes are staged locally until Save.');refresh();return;}$('#space_selection_hint').text((t.type==='space'?'Space ':t.type==='wall'?'Wall ':'Window ')+t.id+' — changes are staged locally until Save.');table.append('<tr><th>Parameters</th><th>Values</th><th>Unit</th></tr>');var v=values(t);(fields[t.type]||[]).forEach(function(f){var e=v[f[0]]==null?'':validate(t.type,f[0],v[f[0]],v);var row=$('<tr><td></td><td><input type="text" class="space-input" autocomplete="off"><span class="field-error" role="status"></span></td><td></td></tr>');row.children().eq(0).text(f[1]);row.find('input').attr('data-field',f[0]).val(v[f[0]]==null?'':v[f[0]]);row.find('.field-error').text(e);row.children().eq(2).text(f[2]);table.append(row);});$('#zone_standard').text(t.type==='space'&&(v.zone_standard||v.zone_template)||'');highlight();refresh();}
  function store(model){UI.space_params=Object.create(null);(model.spaces||[]).forEach(function(entry){var x=entry[0];x.zone_infiltration=x.zone_infiltration==null?x.zone_inflitration:x.zone_infiltration;UI.space_params[String(x.id)]=x;saved['space:'+x.id]=x;});}
  UI.model_action=function(command,params){if(UI.modelBusy||pending)return;if((command==='transform_idf'||command==='main_analysis')&&dirty()&&!UI.draftWarned){UI.draftWarned=true;alert('Unsaved changes: click Save to include them. Click the calculation again to use saved RDF values.');return;}UI.modelBusy=true;refresh();Skp.send(command,params||[]);};
  UI.model_page_status=function(d){if(UI.modelContext!==d.context){UI.modelContext=d.context;drafts=d.drafts||Object.create(null);manifest=null;UI.selectedTarget=null;$('#space_svg_view,#space_level').empty();}UI.settingsVersion=d.settings_version;UI.modelBusy=!!d.busy;if(d.selected_space_id!=null&&String(d.selected_space_id)!==''){var id=String(d.selected_space_id);UI.selectedTarget={type:'space',id:id,values:UI.space_params[id]||{}};}else if(d.selected_element){var e=d.selected_element,k=e.type+':'+e.id;saved[k]=Object.assign({},saved[k]||{},e.settings||{});UI.selectedTarget={type:e.type,id:e.id,values:saved[k]};}else{UI.selectedTarget=null;}render();};
  UI.update_model_data=function(model){$('#building_area').text(Number(model.area||0).toFixed(0));$('#building_height').text(Number(model.height||0).toFixed(1));$('#average_floor_height').text(Number(model.floor_height||0).toFixed(1));store(model);if(UI.selectedTarget&&UI.selectedTarget.type==='space'&&UI.space_params[UI.selectedTarget.id])UI.selectedTarget.values=UI.space_params[UI.selectedTarget.id];render();};
  UI.safe_space_svg=function(s){var d=new DOMParser().parseFromString(s,'image/svg+xml');if(d.querySelector('parsererror'))throw new Error('Invalid SVG');var ok=['svg','g','path','defs','clipPath','rect','text','tspan','use','title','desc'],attrs=['id','class','viewBox','width','height','x','y','x1','y1','x2','y2','d','transform','fill','stroke','stroke-width','fill-rule','clip-path','opacity','style','href','data-space-id','data-element-id','data-element-type','tabindex','role','aria-label','aria-pressed','version'];function clean(n){Array.from(n.children).forEach(function(c){if(ok.indexOf(c.localName)<0)c.remove();else clean(c);});Array.from(n.attributes).forEach(function(a){if(attrs.indexOf(a.localName)<0||/(?:javascript:|https?:|data:|expression\s*\(|@import)/i.test(a.value)||(a.localName==='href'&&a.value.charAt(0)!=='#'))n.removeAttributeNode(a);});}clean(d.documentElement);return document.importNode(d.documentElement,true);};
  function panZoom(svg){var raw=(svg.getAttribute('viewBox')||'').trim().split(/[ ,]+/).map(Number);if(raw.length!==4||raw.some(function(n){return !isFinite(n);}))return;var base={x:raw[0],y:raw[1],w:raw[2],h:raw[3]},box=Object.assign({},base),drag=null;function apply(){svg.setAttribute('viewBox',[box.x,box.y,box.w,box.h].join(' '));}function point(e){var r=svg.getBoundingClientRect();return{x:box.x+(e.clientX-r.left)*box.w/r.width,y:box.y+(e.clientY-r.top)*box.h/r.height};}function reset(){box=Object.assign({},base);apply();}svg.addEventListener('wheel',function(e){e.preventDefault();var p=point(e),factor=e.deltaY<0?.82:1.22,nw=Math.max(base.w/30,Math.min(base.w*5,box.w*factor)),nh=nw*base.h/base.w;box.x=p.x-(p.x-box.x)*nw/box.w;box.y=p.y-(p.y-box.y)*nh/box.h;box.w=nw;box.h=nh;apply();},{passive:false});svg.addEventListener('pointerdown',function(e){if(e.button!==0)return;svg.__suppressClick=false;drag={start:point(e),clientX:e.clientX,clientY:e.clientY,box:Object.assign({},box),moved:false};});svg.addEventListener('pointermove',function(e){if(!drag)return;var dx=e.clientX-drag.clientX,dy=e.clientY-drag.clientY;if(!drag.moved&&Math.sqrt(dx*dx+dy*dy)<4)return;if(!drag.moved){drag.moved=true;if(svg.setPointerCapture)svg.setPointerCapture(e.pointerId);}var p=point(e),start=point({clientX:drag.clientX,clientY:drag.clientY});box.x=drag.box.x-(p.x-start.x);box.y=drag.box.y-(p.y-start.y);apply();});svg.addEventListener('pointerup',function(e){if(drag&&drag.moved){svg.__suppressClick=true;setTimeout(function(){svg.__suppressClick=false;},250);}drag=null;if(svg.hasPointerCapture&&svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);});svg.addEventListener('pointercancel',function(e){drag=null;if(svg.hasPointerCapture&&svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);});svg.addEventListener('dblclick',function(e){e.preventDefault();reset();});}
  function activateHit(svg,e){if(e.type==='keydown'&&e.key!=='Enter'&&e.key!==' '&&e.key!=='Spacebar')return;if(e.type==='click'&&svg.__suppressClick){svg.__suppressClick=false;e.preventDefault();return;}var node=e.target;while(node&&node!==svg&&!(node.nodeType===1&&(node.hasAttribute('data-space-id')||node.hasAttribute('data-element-id'))))node=node.parentNode;if(!node||node===svg)return;e.preventDefault();if(node.hasAttribute('data-element-id'))choose({type:node.getAttribute('data-element-type'),id:node.getAttribute('data-element-id'),values:{}});else{var id=node.getAttribute('data-space-id');choose({type:'space',id:id,values:UI.space_params[id]||{}});}}
  function level(clear){if(!manifest)return;var l=manifest.levels.find(function(x){return x.id===$('#space_level').val();}),v=document.getElementById('space_svg_view');v.textContent='';if(l){var svg=UI.safe_space_svg(l.svg);v.appendChild(svg);panZoom(svg);svg.addEventListener('click',function(e){activateHit(svg,e);});svg.addEventListener('keydown',function(e){activateHit(svg,e);});}if(clear){UI.selectedTarget=null;Skp.send('model_clear_selection',[]);}render();}
  UI.model_svg=function(d){if(d.context!==UI.modelContext)return;$('#space_svg_status').text(d.loading?'Rendering…':d.error||'');if(d.loading||d.error)return;var old=$('#space_level').val();manifest=d;var s=$('#space_level').empty();d.levels.forEach(function(l,i){$('<option>').val(l.id).text('Level '+(i+1)+' · z '+l.elevation.toFixed(3)+' m · '+l.space_count+' spaces').appendTo(s);});if(d.levels.some(function(l){return l.id===old;}))s.val(old);$('#space_svg_warnings').text((d.warnings||[]).join('\n'));level(false);};
  function choose(t){if(UI.modelBusy||pending)return;flush();UI.selectedTarget=t;if(t.type==='space')UI.model_action('show_space',[t.id]);else UI.model_action('show_element',[t.id,t.type]);render();}
  function save(){if(!dirty()||pending)return;flush();var items=Object.keys(drafts).filter(function(k){return Object.keys(drafts[k]).length;}).map(function(k){var p=k.indexOf(':'),type=k.slice(0,p),id=k.slice(p+1);return {type:type,id:id,values:drafts[k],current_values:saved[k]||{}};});pending=true;refresh();Skp.send('space_batch_save',[JSON.stringify({request_id:'batch-'+Date.now(),context:UI.modelContext,settings_version:UI.settingsVersion,items:items})]);}
  UI.space_batch_result=function(d){if(d.context!==UI.modelContext)return;UI.settingsVersion=d.revision;(d.items||[]).forEach(function(i){var k=i.type+':'+i.id;saved[k]=Object.assign({},saved[k]||{},i.values);delete drafts[k];});pending=false;UI.draftWarned=false;render();};UI.space_batch_error=function(d){pending=false;alert(d.message||'Save failed');render();};
  $(function(){var cmds={recognize_btn:'recognize_model',enable_visualize_entity_type:'visualize_entity_type',disable_visualize_entity_type:'disable_visualize_entity_type',show_all_face:'show_all_face'};Object.keys(cmds).forEach(function(i){$('#'+i).off('click').on('click',function(){UI.model_action(cmds[i]);});});$('#space_save').on('click',save);$('#space_reset').on('click',function(){drafts=Object.create(null);flush();UI.draftWarned=false;render();});$('#space_level').on('change',function(){level(true);});$('#building_params_table').on('input','.space-input',function(){if(!UI.selectedTarget)return;var k=key(UI.selectedTarget);drafts[k]=drafts[k]||{};drafts[k][this.getAttribute('data-field')]=this.value;UI.draftWarned=false;render();schedule();}).on('keydown','.space-input',function(e){if(e.key==='Enter'){e.preventDefault();flush();}if(e.key==='Escape'){var k=key(UI.selectedTarget);if(drafts[k])delete drafts[k][this.getAttribute('data-field')];render();schedule();}});Skp.send('update_model_data',[]);});
}());
